name: saude_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.1 # Required for Firebase
  firebase_auth: ^5.5.1 # For Firebase Authentication
  cloud_firestore: ^5.3.1 # For Firestore Database
  firebase_storage: ^12.2.1 # For Firebase Storage
  flutter_riverpod: ^2.5.1 # For state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

