// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFaXX0aexz0reAkYXq4xVWMZb0EVhifEc',
    appId: '1:596204006655:web:2dbb898b850fc6cb6370ca',
    messagingSenderId: '596204006655',
    projectId: 'saudeapp-69c5a',
    authDomain: 'saudeapp-69c5a.firebaseapp.com',
    storageBucket: 'saudeapp-69c5a.firebasestorage.app',
    measurementId: 'G-9TTL6W7FYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9iAousxoWlTJuhTG_ZB7rpVNdN524nX0',
    appId: '1:596204006655:android:4372b786484dfe8f6370ca',
    messagingSenderId: '596204006655',
    projectId: 'saudeapp-69c5a',
    storageBucket: 'saudeapp-69c5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgeBAiItL7JgjPylM-p1XRFgi9rvP3810',
    appId: '1:596204006655:ios:2bd9e1fdd52e31146370ca',
    messagingSenderId: '596204006655',
    projectId: 'saudeapp-69c5a',
    storageBucket: 'saudeapp-69c5a.firebasestorage.app',
    iosClientId: '596204006655-cj1kvdl758qcid39b7ml5767oudlj9h9.apps.googleusercontent.com',
    iosBundleId: 'com.rafaelopa.saudeApp',
  );
}
