import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:saude_app/firebase_options.dart'; // Will be generated by FlutterFire CLI
import 'package:saude_app/src/features/authentication/presentation/screens/login_screen.dart'; // Placeholder
// import 'package:saude_app/src/features/authentication/presentation/widgets/auth_gate.dart'; // Placeholder for later

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Uses generated options
  );
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Saúde App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // TODO: Replace with AuthGate once implemented
      home: const LoginScreen(), // Initially show LoginScreen
    );
  }
}

